/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "./Header";
import Navigation from "./Navigation";
import HeroSection from "./HeroSection";
import AboutSection from "./AboutSection";
import InfoSection from "./InfoSection";
import SearchTrendsSection from "./SearchTrendsSection";
import NewsletterSection from "./NewsletterSection";
import Footer from "./Footer";

function App() {
  return (
    <div className="flex flex-col items-end px-20 max-md:pl-5">
      <div className="flex flex-col w-full max-md:max-w-full">
        <Header />
        <Navigation />
        <main>
          <HeroSection />
          <AboutSection />
          <InfoSection />
          <SearchTrendsSection />
          <NewsletterSection />
        </main>
        <Footer />
      </div>
    </div>
  );
}

export default App;
