/**
 * This code was generated by Builder.io.
 */
import React from 'react';

function CursorColorButton() {
  return (
    <div className="flex gap-1 items-center self-stretch my-auto text-lg font-medium text-center text-white">
      <div className="self-stretch my-auto">Cursor color</div>
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/49dc7984d3829d8d6eb1403482ff48bd998f5da793509ae3b13b5c45d62f43ae?placeholderIfAbsent=true&apiKey=d56f8d62d9074d509de3faeb2651bd99"
        alt=""
        className="object-contain shrink-0 self-stretch my-auto w-4 aspect-square"
      />
    </div>
  );
}

export default CursorColorButton;
