/**
 * This code was generated by Builder.io.
 */
import React from 'react';

function FullscreenButton() {
  return (
    <div className="flex gap-1 items-center self-stretch my-auto">
      <div className="flex overflow-hidden gap-2.5 items-center self-stretch p-0.5 my-auto w-6 bg-red-700 border border-white border-solid min-h-[12px] rounded-[1000px]">
        <div className="flex self-stretch my-auto w-2 h-2 bg-pink-50 min-h-[8px] rounded-[10000px]" />
      </div>
      <div className="self-stretch my-auto text-lg font-medium text-center text-slate-100">
        Fullscreen
      </div>
    </div>
  );
}

export default FullscreenButton;
