/**
 * This code was generated by Builder.io.
 */
import React from "react";

function SearchSite() {
  return (
    <div className="flex gap-4 items-center self-stretch my-auto min-w-[240px]">
      <div className="flex gap-1 justify-center items-center self-stretch px-2 py-px my-auto w-56 text-xl text-red-600 border-b border-solid border-b-red-600 min-h-[32px]">
        <div className="flex-1 shrink self-stretch my-auto basis-0">
          Search site
        </div>
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/c70aea4b9bd6a6cd42a0bd209b4976c9051334994b2f8377e4d3446abf95f7a6?placeholderIfAbsent=true&apiKey=d56f8d62d9074d509de3faeb2651bd99"
          alt=""
          className="object-contain shrink-0 self-stretch my-auto w-6 aspect-square"
        />
      </div>
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/ce29b1d37fff06604c2f959bd9c42e5c90d68970b7b761e0f05afbb5099ff8cf?placeholderIfAbsent=true&apiKey=d56f8d62d9074d509de3faeb2651bd99"
        alt=""
        className="object-contain shrink-0 self-stretch my-auto w-9 aspect-square"
      />
      <div className="flex overflow-hidden flex-col justify-center items-center self-stretch my-auto w-9 h-9 bg-red-600 rounded min-h-[36px]">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/69cc005fb5aa48a30fdee707e2fad1dfaa28d762782c2cdab22d52af15a8d301?placeholderIfAbsent=true&apiKey=d56f8d62d9074d509de3faeb2651bd99"
          alt=""
          className="object-contain w-6 aspect-square"
        />
      </div>
    </div>
  );
}

export default SearchSite;
